name: Print GitHub Environment Variables

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: Environment name
        required: true
        default: 'dev'
        type: choice
        options:
          - 'dev'
          - 'test'
env:
  environment: ${{ github.event.inputs.environment || 'dev' }}
  account: ${{ secrets.account }}

jobs:
  print-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure variables
        run: |
           runningEnv=${{ env.environment }}
           runningAccount=${{ env.account }}
           echo "$runningEnv"
           echo "$runningAccount"

